# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: pygments
markdown: kramdown
disqus: dbyll
google_analytics: dbyll
title: Nirvana

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Nirvana

description: Stylish Jekyll Theme
author:
  name: Li Yang
  email: liyangsh48@gmail.com
  github: ColdCodeCool
  twitter: dbtek
  pinterest: asd123
  linkedin: asd123
  bio: Know more! Do more! Do better!
  email_md5: 726351295ec82e145928582f595aa3aa

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

# set it as url of an image
#sidebar_background_image: http://www.overpic.net/viewer.php?file=xxqkpqthbprqv3xh241d.png

BASE_PATH: 

gems:
  - jekyll-paginate