# Site settings
name: Li Yang
description: "Know more! Do more! Do better!"
url: "liyangstu.com"


# Delete the lines you don't need
# about 5 elements are recomended
github_username:  ColdCodeCool
twitter_username: your_twitter_username_goes_here
google_plus_username: your_google_plus_username_goes_here
linked_in_username: your_linked_in_username_goes_here
weibo_username: your_weibo_username_goes_here
blog_url: "/ColdCodeCool.github.io"
email: liyangsh48@gmail.com
public_key_url: "https://raw.pastebin.com/LINK-TO-PUBLIC-KEY"


avatar: yes
#avatar_img_path: "imgs/avatar.jpg""
# You can link to your GitHub image. That way it will get updated 
# automatically whenever you change your GitHub profile picture
avatar_img_path: "https://avatars2.githubusercontent.com/u/17301305"


front_img: yes
front_img_path: "imgs/background.jpg"
#front_img_path: "https://external.url/image.jpg"

# Build settings
markdown: kramdown
permalink: pretty
